version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Navigating to jellyspace directory..."
      - cd jellyspace
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Building the application..."
      - cd jellyspace
      - npm run build
artifacts:
  files:
    - jellyspace/dist/**/*  # Update this path if the build output location differs
