version: 0.2

phases:
  install:
    commands:
      - echo "Navigating to jellyspace directory..."
      - cd jellyspace
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Preparing build environment..."
      - cd jellyspace  # Ensure you are in the correct directory
  build:
    commands:
      - echo "Building the application..."
      - cd jellyspace  # Ensure you are in the correct directory
      - npm run build
