version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - cd jellyspace  # Navigate to the jellyspace directory where package.json is located
      - npm install    # Run npm install inside jellyspace
  build:
    commands:
      - echo Building the application...
      - cd jellyspace  # Navigate to the jellyspace directory again (if not already there)
      - npm run build  # Run the build command inside jellyspace

artifacts:
  files:
    - jellyspace/build/**/*  # Assuming the build output is in the build folder inside jellyspace
